import Head from 'next/head'
import Feed from '../components/Feed'
import Sidebar from '../components/Sidebar'
import Widget from '../components/Widget'
import CommentModal from '../components/CommentModal'

export default function Home({newsResults, randomUserResult}) {
  return (
    <div>
      <Head>
        <title>Waterd</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen mx-auto">

        {/* sidebar */}
        <Sidebar />

        {/* Feed */}
        <Feed />

        {/* Widget */}

        <Widget newsResults={newsResults.articles} randomUserResult={randomUserResult.results}/>

        {/* Modal */}
        <CommentModal />
      </main>
    </div>
  )
}


//https://saurav.tech/NewsAPI/top-headlines/category/business/us.json

export async function getServerSideProps() {
  const newsResults = await fetch ("https://saurav.tech/NewsAPI/top-headlines/category/business/us.json").then((res) => res.json());

  /* Who to follow section */

  const randomUserResult = await fetch("https://randomuser.me/api/?results=50&inc=name,login,picture").then((res) => res.json());
  return {
    props:{
      newsResults,
      randomUserResult,
    }
  }
}